### ISSUE TITLE
Get Label As PDF return weird characters

### ISSUE THREAD

**Issue by kaidenhollander** [imbue/sendcloud-api-php#5]
Hey,

When I try to get the Label as PDF it does not download any printable PDF file but it shows a white screen.

When I do: `echo $sendCloud->labels->getLabelAsPDF($shipment_id,'label_printer');` it shows me this:

<img width="1440" alt="Scherm­afbeelding 2023-06-06 om 00 22 18" src="https://github.com/imbue/sendcloud-api-php/assets/107953338/a2bccce2-1c25-43b9-bcd2-4d89fb26947d">

Any solution for this, maybe I'm just doing something wrong?

**Comment by imbue** [comment]
Hi @kaidenhollander,

You're actually looking at the bytes of the pdf here. Try setting the right pdf headers with your response. Assuming you're using something like Laravel you can try the following:

```php
$headers = [
    'Content-Type' => 'application/pdf',
    'Content-Disposition' => 'attachment; filename="your_filename.pdf"',
];

return response($pdf, 200, $headers);
```

**Comment by kaidenhollander** [comment]
Thanks! Solved.
